/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChildElement {
    }
    interface ChildElementSecond {
    }
    interface ElementBase {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLChildElementElement extends Components.ChildElement, HTMLStencilElement {
    }
    var HTMLChildElementElement: {
        prototype: HTMLChildElementElement;
        new (): HTMLChildElementElement;
    };
    interface HTMLChildElementSecondElement extends Components.ChildElementSecond, HTMLStencilElement {
    }
    var HTMLChildElementSecondElement: {
        prototype: HTMLChildElementSecondElement;
        new (): HTMLChildElementSecondElement;
    };
    interface HTMLElementBaseElement extends Components.ElementBase, HTMLStencilElement {
    }
    var HTMLElementBaseElement: {
        prototype: HTMLElementBaseElement;
        new (): HTMLElementBaseElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "child-element": HTMLChildElementElement;
        "child-element-second": HTMLChildElementSecondElement;
        "element-base": HTMLElementBaseElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChildElement {
    }
    interface ChildElementSecond {
    }
    interface ElementBase {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "child-element": ChildElement;
        "child-element-second": ChildElementSecond;
        "element-base": ElementBase;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "child-element": LocalJSX.ChildElement & JSXBase.HTMLAttributes<HTMLChildElementElement>;
            "child-element-second": LocalJSX.ChildElementSecond & JSXBase.HTMLAttributes<HTMLChildElementSecondElement>;
            "element-base": LocalJSX.ElementBase & JSXBase.HTMLAttributes<HTMLElementBaseElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
